-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 08, 2023 at 09:20 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `website_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `cat_id` int(11) NOT NULL,
  `cat_title` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`cat_id`, `cat_title`) VALUES
(1, 'Dolls'),
(2, 'Puzzles'),
(3, 'Board Games'),
(4, 'Figurines'),
(5, 'Lego'),
(6, 'Electronics');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `product_id` int(11) NOT NULL,
  `product_title` varchar(255) NOT NULL,
  `product_category_id` int(11) NOT NULL,
  `product_price` float NOT NULL,
  `product_quantity` int(11) NOT NULL,
  `product_description` text NOT NULL,
  `product_short_desc` text NOT NULL,
  `product_image` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_id`, `product_title`, `product_category_id`, `product_price`, `product_quantity`, `product_description`, `product_short_desc`, `product_image`) VALUES
(1, 'Barbie Be a Fashion Designer Doll Dress Up Kit', 1, 349.99, 9, 'Design Your Own Barbie Doll Fashions With The Barbie Be A Fashion Designer Dress Up Kit\r\nKit Includes 5 Dresses To Design And Decorate With Ribbons, Bows, Glitter, And Other Fun Accessories\r\nCountry Of Origin : United States\r\nApply Ribbons, Bows, Glitter, And Other Fun Accessories\r\n', 'A variety of clothes available for you to choose!', 'Barbie1.jpeg'),
(2, 'Disney Princess DPR Shimmer Snow White', 1, 249.99, 15, 'Snow White has shimmery glitter eyes and her signature black hair to style. This gorgeous Princess is approximately 14 inches tall. Includes doll, removable dress, shoes and Tiara. Also look for the matching Snow White girl dress! (sold separately) Recommended for ages 3+', 'Disney Princess My Friend Snow White Doll 14 inch', 'SnowWhite.jpeg'),
(3, 'Marvel Ultimate Spider-man Titan Hero ', 4, 350, 12, 'The realistic figure has 4 joints, including head, arms, legs, and feet. The head, arms and feet can be rotated 360 degrees, and the legs can swing forward and backward. Flexible joints not only improve your child\'s hands-on ability, but also improve imagination.he figure is made of eco-friendly and high-quality PVC materials, which is ideal for use as interior decoration displays and collections.', 'Series Spider-man Figure, 12-Inch', 'S.jpeg'),
(4, 'Barbie Camper, Doll Playset with 50 Accessories', 1, 850, 5, 'Transform the colorful Barbie DreamCamper into a campsite play set with the push of a button -the top pops up, the side pops out and the back expands to create a play space more than 2 feet long\r\nThe open side becomes a pool with a water slide and stairs that fold out to really make a splash\r\nUse the interior to eat or sleep -pull up the two seats from the front cab to create chairs for the table or hook up the hammocks to let two sisters sleep under the stars\r\nTwo more beds mean Barbie doll and all of her sisters can hit the road together (dolls sold separately)', 'Includes Waterslide, 2 Hammocks, Canopy Bed & Fireplace, Dream Camper.\r\n', 'BarbieS.png'),
(5, 'Disney Frozen Toys, Singing Elsa Doll in Signature Clothing ', 1, 349.99, 5, 'Inspired by the beloved animated character, this Elsa doll sings her celebrated song from Disney\'s Frozen!\r\nKids can press a button and join in as the Elsa doll sings a 30-second clip from her signature song, in English: \"Let It Go.\"\r\nElsa doll wears her classic blue outfit from the first Disney Frozen movie, with removable soft cape.\r\nShe also has soft, brushable hair and an authentic braided hairstyle from the movie.', 'Sings “Let It Go” from The Disney Movie Frozen', 'Elsa.jpeg'),
(6, 'Adora Realistic Baby Doll All Star Toddler Doll', 1, 399.99, 8, 'Interactive doll: Makes 5 sounds when your child plays with her. She Cries, Coos, Giggles, Kisses Back & Says Momma\r\nReacts to play: Squeeze her hand and she’ll cry. Pat her head to hear her coo. Tickle her tummy to hear sweet giggles. Kiss her cheek and she’ll kiss you back. Pat her head and she’ll call you Momma', '20 inch, Soft CuddleMe Vinyl, Brown Hair, Brown Eyes', 'TG.jpg'),
(7, 'Soft Body Interactive Baby Doll', 1, 349.99, 10, 'Realistic Newborn Baby Dolls - Your \"little parent\" will love to care for this perfectly cute baby doll. Dolly has a lot of cute details. Her Arms, Legs, head and face are made of vinyl with a body that is soft and huggable. Her talking, laughing and crying sound features help toddlers, boys and girls create an awareness of their own real life emotions.', 'Can Talk, Cry, Sing and Laugh - Makes Cute Gibberish Sounds', 'TalkingBoy.jpeg'),
(9, '4 Inch Purple Fairy', 4, 500, 13, 'ENESCO FIGURINE: from the Disney Traditions by Jim Shore Collection, titled \"Ecstatic Elf\"\r\nDESIGN: combines Jim Shore\'s unmistakable style of traditional themes and quilt patterns with classic and modern Disney characters!\r\nHAND-CRAFTED: from high-quality stone resin and hand-painted with intricate styling and attention to detail', 'Sitting and Reading a Book Statue Figurine, Blue', 'x.jpg'),
(10, 'TAMASHII NATIONS - Naruto Shippuden - Naruto Uzumaki', 4, 449.99, 8, 'Naruto Uzumaki, as seen in \"NARUTO: Shippuden,\" rejoins S.H.Figuarts with all new joint technology\r\n[Set Contents] Main Body, Three left and four right optional hands, Four optional expressions, Kunai, \"Rasengan\" effect, Crossed arm parts\r\nStands approximately 5.5\" tall', '15 inch Naruto Figurine', 'd.jpg'),
(11, 'DC Comics, 12-inch Batman Action Figure', 4, 350, 7, '12-INCH ACTION FIGURE: With 11 points of articulation, it’s easy to pose this 12-inch Batman action figure into a variety of dynamic action poses. Create your own Batman pretend play adventures!\r\nAUTHENTIC COMIC STYLING: This articulated action figure is highly detailed, featuring a cloth cape and comic styling that brings your favorite Batman toys to life!\r\nCOLLECT THEM ALL: Bring the excitement of Batman home! Add Batman, Nightwing, Red Hood, The Joker and more to your Batman toy figures & playsets collection (each sold separately)!\r\nFANS AND COLLECTORS: This Batman 12-inch collectible Action Figure is a must-have Batman toy for fans and Justice League collectors!', 'Kids Toys for Boys and Girls Ages 3 and Up', 'B.jpg'),
(12, 'Goku Figure Statues Figurine DBZ Super Saiyan ssj3 Collection', 4, 299.99, 15, 'Simple construction patterns ensure it will be an easy to build figure even for those who have never built a model kit before!This Goku Statue Is A Great Gift Idea For Kids ( girls ) In any occasion !', 'Goku Figure Statues Figurine DBZ Super Saiyan ssj3 Collection', 'Goku.jpeg'),
(13, 'Farm Animals Figurines Toys, 53PCS Realistic Plastic ', 4, 259.99, 23, 'CHILD FRIENDLY & HIGH QUALITY: Farm Animal figurines are made of high quality durable ABS materials which is Eco-Friendly. BOLZRA\'s #1 priority is child safety. Please note this is designed for baby children ages 3 and up.\r\nREALISTIC FARM ANIMALS: 14PCS unique non-repeating plastic farm animals with vibrant colors, 8 pcs unique 4-5 inch big farm animals and 6 pcs 2 inch mini farm animals. Including Cow, Goat, Sheep, Dog, Dairy cattle, Donkey, Horse, Hen, Rooster, Goose, Duck, Pig. All accessories are in the storage box.', 'Farm Playset with Fences Soil Puzzle Blocks', 'm.jpg'),
(14, 'Star Wars Galactic Action The Mandalorian & Grogu', 4, 189.99, 19, 'FIGURE AND ACCESSORY-ACTIVATED: Protect Grogu at all costs by snuggling him into The Mandalorian\'s satchel to hear them interact, then attach his jetpack to enjoy even more galactic sound FX\r\nADDITIONAL REMOVEABLE ACCESSORY: These Galactic Action The Mandalorian & Grogu toys also come with a blaster inspired by The Mandalorian\r\n15 SERIES-INSPIRED SOUNDS: Activate 15 different sounds and phrases inspired by The Mandalorian through multiple ways of play, including pressing the button on the bounty hunter\'s chest', '12-Inch-Scale Action Figures, Toys for Kids Ages 4 and Up', 'r.jpg'),
(15, 'Logic Roots Pet Me Multiplication and Division Game ', 3, 450, 17, 'HAVE FUN WITH MULTIPLICATION AND DIVISION: Pet Me is an exciting math board game. Kids go on a pet park adventure, feed dogs, cats and parrots, win hearts and adopt them. They will master multiplication and division facts along the way. A very cool and fun game that builds mental math skills.\r\nMULTIPLE SKILL LEVELS AND 4X MORE PRACTICE - It has a host of engaging levels with math integrated in each step. Perfect for kids between the ages of 5 to 9 (grade 1 and up) and aligned with elementary school education. Beginners level and adaptable rules make it suitable for younger players too.', 'Fun Math Board Game for 5 - 9 Year Olds', 's.jpg'),
(16, 'Chutes and Ladders Board Game', 3, 250.99, 9, 'Ages:4 and up, Players:2 to 4\r\nFun without Words: ‘Chutes and Ladders’ is simple and easy to play, with no reading required. Be First to land on the 100 spot and win the game\r\nUP THE LADDERS AND DOWN THE CHUTES: Land on good deeds and climb ladders toward the winning spot. Land on bad deeds and ride the chutes back down\r\nTEACHES BASIC SKILLS: Great for kids who are learning to count, this game encourages basic addition skills', 'An exciting Up and Down game for children', 'q.jpg'),
(17, 'Monopoly Junior Dinosaur Edition Board Game', 3, 1299.99, 5, 'KIDS MONOPOLY GAME: DINOSAUR EDITION: In this Monopoly Junior board game, kids can imagine a world in which they come face-to-face with different kinds of dinosaurs and feed them leafy banknotes. Family board games everyone will love.\r\nFUN GAME FOR KIDS: Players can imagine making friends with the dino toys by feeding them. The Brontosaurus and Iguanadon are pretty affordable, but it\'s going to cost a lot to feed the Gigantosaurus. One of the funnest childrens games to add to the collection of dinosaur toys for kids.\r\nDINOSAUR NAMES: The gameboard spaces feature phonetic spellings of different kinds of dinosaurs so caregivers can help kids practice saying different dinosaur names', 'Kids Board Games, Fun Dinosaur Toys, Dinosaur Board Game for 2-4 players', 'e.jpg'),
(18, 'Travofun 2 in 1 Board Games for Kids Checkers Sets Board Games for Kids  ', 3, 479.99, 4, 'Checkers & Tic-Tac-Toe Children Board Games - BST SHIER is bringing fun and exciting 3-fold travel toys which include Eva checkers board game for kids and Tic-tac-toe game for kids 3-10 years to enjoy while traveling or as group activity. Checkers printed on EVA material & paper and foldable to fit in small backpack. Easy To Store, Light Weight, & Uniquely Designed - BST SHIER checkers & tic tac toe outdoor game opens just like a book and its simple 3-fold design makes it easy for children to carry anywhere.', 'AxcessAbles Isolation Pads, Audio Cables and eStudioStar Polishing', 'l.jpg'),
(19, 'NEILDEN Disney Frozen Puzzles in a Metal Box 60 Piece Jigsaw Puzzle for Kids', 2, 449.99, 9, 'The pieces of Frozen jigsaw puzzles are made of nontoxic and odorless material which are sturdy enough and do not tear easily so good for children. The die-cuts of kids puzzles are smooth, allowing for easy assembly\r\nClassic Storage Box: Frozen jigsaw puzzle comes with a metal box which is quite convenient to store and takes for travel. The pieces will not be lost as well . Kids enjoy doing puzzles and form good habits of integrating things', 'Puzzle for Kids Ages 3+ for Children Learning Educational Puzzles Toys (Snowman) Authorized by Disney', 'k.png'),
(20, 'Puzzles for Kids Ages 4-8 60 Pieces Jigsaw Puzzles for Boys and Girls', 2, 449.99, 24, '1-Package Containt: 60 pieces puzzles and a 1:1 reference poster that will help chirldren to finish the puzzle. One metal box help storage every pieces conveniently.\r\n2-Puzzle Size: The jigsaw puzzle has 60 pieces, it\'s perfect for children ages 4-8 years old. The size of every single piece:1.5\'*1\'. Finished size: 9.5\'*6\'.Metal box size: 3.25\'*5.25\'.\r\n3-High Quality: Every piece is unique, complete cutting and fits perfectly. We produce our jigsaw puzzle toys of 100% safe high-quality materials & FSC compliant wood that meet Safety Standards', 'Puzzles for Kids Ages 4-8 60 Pieces Jigsaw Puzzles for Boys and Girls Educational Learning Puzzles in Metal Box Thomas ', 'v.jpg'),
(21, 'LELEMON Disney Car Jigsaw Puzzles in a Metal Box 60 Pieces Lightning McQueen', 2, 449.99, 5, '🚒60 Pieces Puzzles for Kids🚒 -- Every Package Includes Puzzle Pieces, a Tin Box, An Original Picture. Sturdy Boxes Are Perfect For Gifting, Stacking And Storage. Puzzles Can Bring Entertainment And Fun Time To Everyone! and Help Children Gain A Sense Of Accomplishment In The Puzzle Process.', 'McQueen Jigsaw Puzzle for Kids Ages 4-8 Children Learning Educational Puzzles Toys', 'u.png'),
(25, 'LELEMON Disney Mickey Mouse Puzzle for Kids Ages 4-8 in a Metal Box 100 Piece ', 2, 549.99, 5, 'Puzzles for Kids: LELEMON Disney Mickey Mouse 100 Pieces Puzzles come in a tin box for easy storage and not easy to lose puzzle pieces. Playing puzzles can stimulate children\'s reasoning and thinking skills, improve hand-eye coordination, and improve children\'s resistance to frustration.\r\nHigh Quality Material: Jigsaw puzzles are made of non-toxic and odorless material. The surface pattern is vivid and clear, smooth and easy to clean. We use precision cutting techniques to ensure that each puzzle piece fits perfectly, which is sturdy and secure.\r\nBenefits of Playing Puzzles: Puzzles make children smarter, develop children\'s observation, patience and concentration, and help children build self-confidence. In the learning of puzzles, children will gradually develop various strategies and learn to sort out the clues to complete the puzzle from the chaos.', 'For Kids Ages 4-8 in a Metal Box 100 Piece Learning Educational Puzzles for Children Girls and Boys(Mickey & Minnie)', 'i.jpg'),
(26, 'Mudpuppy Animals of The World Puzzle Sticks', 2, 1000, 15, '6 PUZZLES IN ONE – The Animals of the World Puzzle Sticks from Mudpuppy includes 24 double-sided puzzle sticks that create six unique eight-piece puzzles!\r\nCOLORFUL DESIGNS – This is a unique and easy puzzle for toddlers and children Sort the sticks by background colors, then use the included tray to arrange the sticks in the correct order to reveal a colorful penguin, whale, red panda, turtle, koala and lion', '24 Double-Sided Sticks Create 6 Different Puzzles – Unique Animal Puzzles for Kids Ages 3-6 – Puzzle Tray and Drawer Box Included, Multicolor', 'h.jpg'),
(27, 'Lego Technic Bugatti Chiron', 5, 4500, 5, 'The perfect gift for car lovers and future engineers! Build and experience a quintessential collectible sports car – the LEGO Technic Bugatti Chiron! Developed in partnership with Bugatti Automobiles S.A.S, this is a faithful recreation of the real car. You can now answer the question: \"What colour is your Bugatti?\".', '42083 Race Car Building Kit and Engineering Toy, Adult Collectible Sports Car with Scale Model Engine (3599 Pieces)', 'bugatti.png'),
(28, 'Lego Star Wars X-Wing Fighter', 5, 3500, 5, 'Features a LEGO brick-built version of Luke Skywalker’s iconic toy X-wing Fighter to recreate scenes from the classic Star Wars trilogy. The X-wing features an opening LEGO minifigure cockpit, space for R2-D2 droid and wings that can be switched to attack position with a button\r\nThe X-wing buildable toy also features retractable landing gear and 2 spring-loaded shooters, plus an R2-D2 LEGO droid figure to fit in\r\nIncludes Luke Skywalker, Princess Leia and General Dodonna LEGO Star Wars minifigures with weapons including Luke’s lightsaber\r\nThis set comes with step-by-step, illustrated instructions so even first time young builders can build with Jedi-like confidence\r\nThis LEGO Star Wars X-wing building toy makes a super birthday present or Christmas gift for 9 plus year old boys and girls', '75301 Building Toy, Gifts for Kids, Boys & Girls with Princess Leia Minifigure and R2-D2 Droid Figure', 'LegoStarWars.png'),
(29, 'LEGO Creator 3 in 1 Exotic Parrot to Frog to Fish ', 5, 1500, 3, 'This LEGO Creator 3in1 animal toy set features 3 animals for kids 7+ years old: a parrot toy perched on a branch, a playful frog and a toy fish\r\nThe toy parrot is richly colored and comes with jointed parts that allow it to rotate its body on the branch and move its wings and tail\r\nThe parrot can be rebuilt into a toy frog with posable legs or into a LEGO fish with movable fins and a seabed for creative adventures\r\nKids can choose their building adventure with 3 LEGO Creator animal figures or fire up their imagination and create a new animal with the bricks\r\nWith details such as the parrot\'s branch covered in flowers, this building toy set will look awesome on display in kids\' rooms when play is over\r\nThe easy-to-follow picture guide makes construction easy and fun, plus digital building instructions can also be found in the LEGO Builder app\r\nThis set makes a great Easter basket stuffer for girls and boys\r\nThe parrot toy measures over 22 cm (8.5 in.) high, 11 cm (4 in.) long and 12 cm (4.5 in.) wide. Contains 253 pieces', 'Frog to Fish 31136 Animal Figures Building Toy, Creative Toys and Easter Gift for Kids Ages 7 and up', 'LegoParrot.png'),
(30, 'Brickyard Building Blocks', 5, 1200, 12, 'More Pieces Than Other Sets Of Similar Price - We give you 20% more blocks than other similar sets. It is the most value set on Amazon in terms of versatility and number of pieces\r\nGreater Variety Of Blocks - While other sets contain only 2 different shapes of blocks (square and rectangular), Brickyard Large Building Blocks includes 9 different block shapes (including blocks with printed eyes), allowing for greater versatility, flexibility, and more ways to build\r\nBonus! Includes Building Ideas - At last, a building block set that includes a colorful building ideas guide in every box. This set contains enough building blocks to build 23 different figures at the same time\r\nCompatible With Duplo - Works with all major brands. Because we\'re so confident you\'ll love this 100% compatible building block set, it\'s backed by our No-Hassle Satisfaction Guarantee. If you don\'t love it for any reason, you can return it for a full refund\r\nMeets All U.S. Toy Safety Standards - We manufacture our products using only child-friendly materials and regularly conduct rigorous lab tests to make sure your kids are 100% safe from harmful chemicals. Your kid\'s safety is our #1 priority!', ' 177 Pieces Large Building Block Toys for Children Ages 1.5 - 5, Bulk Block Set, Compatible with Duplo (177 pcs)', 'LegoBB.png'),
(31, 'LEGO City Farmers Market Van ', 5, 2000, 5, 'Children with a passion for shop play will love the LEGO City Farmers Market Van (60345), packed with inspiring details and functions for hours of imaginative play\r\nAll kids need to build a mobile farm shop and veggie patch, with lots of play-inspiring features, plus 3 minifigures, including a LEGO City TV character, and a rabbit figure\r\nThe Farmers Market Van comes with a serving window, opening side doors, rear doors and a minifigure cab, while the veggie patch features a fun carrot-growing function\r\nThe Farmers Market Van playset can be given as a holiday, birthday or any-other-day gift for boys and girls aged 5 and up\r\nDimensions – When built, the LEGO City Farmers Market Van measures over 4 in. (10 cm) high, 10 in. (25 cm) long and 6.5 in. (17 cm) wide', '60345 Building Toy Set for Kids, Boys, and Girls Ages 5+ Mobile Farm Shop Playset with 3 Minifigures (310 Pieces)', 'LegoCity.png'),
(32, 'LEGO Marvel I am Groot!', 5, 499.99, 15, 'Movable Baby Groot – The LEGO Marvel I am Groot (76217) build-and-play model is easy to position and pose\r\nIconic Marvel character – Kids build their own Baby Groot, from Marvel Studios’ Guardians of the Galaxy Vol. 2. The set also includes a pretend cassette tape and display nameplate\r\nRecreate dance moves – The buildable model is easy to position and pose, and there’s even a pretend cassette tape included for make-believe music\r\nGift for kids – A special birthday, holiday or any-day treat for kids aged 10 and up who are fans of Marvel Studios’ Guardians of the Galaxy movies and the super cute Baby Groot\r\nBuild, play and display – The highly posable model stands over 10.5 in. (26 cm) tall and comes with a cassette and a nameplate.', '76217 Building Toy Set for Kids, Boys, and Girls Ages 10+ (476 Pieces)', 'LegoGroot.png'),
(33, 'LELEMON 100 Pieces Spiderman Jigsaw Puzzles', 2, 549.99, 6, '🎮Puzzles for Kids🎮-- The Jigsaw Puzzles Come with A Tin Box, Convenient to Storage And Not Easy to Lose Puzzles Piece.Many Kids Like to Make Jigsaw Puzzles, And Through Puzzle Learning, Kids Will Gradually Develop Various Strategies , And Learning to Sort Out The Clues of Completing The Puzzle from The Chaos Can Help Kid Improve Their Problem-solving Skills.\r\n🎮High Quality Material🎮-- The Puzzle Are Made of Nontoxic And Tasteless Material,Vibrant and Clear Surface,Smooth and Easy to Clean.and We Using A Precision Cutting Technique That Assures Every Piece Will Fit Perfectly,Sturdy and Safe.\r\n🎮Skills Development🎮 -- The Puzzles Will Offer Various of Education Opportunities for Kids,exercise Children\'s Thinking And Logic Skills,develop Operational And Patient Skills.and The Vibrant Colors Attract Children\'s Attention And Are Easily Accepted And Loved By Them.\r\n\r\n', 'In a Metal Box for Kids Age for 4-8 Boys Girls Toy Puzzles Children Learning Educational Puzzles Toys', 'Spidermanpuzzle.png'),
(34, 'Slot Car Race Track Sets', 6, 850, 6, 'Realistic Racing Track: Our slot car race track sets simulates a variety of racing tracks, including simple straight track, S-shaped track, circular track and exciting double-layer overpass track. Bring the coolest racing experience to the racers. At the same time, our race track has an automatic lap counting function, which can record the status of the race in real time, allowing the racers to concentrate on the race.\r\nTwice the Fun for Two Players: Our race car track for boys age 4-7 8-12 is car toy for two racers, it comes with four slot cars, two durable remote controls (tested over 10,000 times). This is not just a friendship toy, but also a family toy, you can compete with your child, a great alternative to video games.\r\nExtra Long Tracks for Easy Installation: The slot car track is 18.4 ft long, which is longer than most other products, and has a better system to lock into place and easy to assemble. In order to keep the car on the track better, we have enhanced the magnetism, but it is also important to control the speed, remember to slow down when turning. In addition, we also prepare extra brushes on the bottom of the car for you, which you can replace at any time.\r\nExciting High-Speed Racing: Our race car can reach a speed of about 300-370 mph on the electric race track, and you can fully feel the power and speed of the racing car in remote control racing. Plus, our kids race track set has two power modes, electric or 6xAA battery(not included), so your kids can experience the fun of racing at home or on the go.', ' with 4 High-Speed Slot Cars, Battery or Electric Race Car Track for Boys and Kids, Dual Racing Game Lap Counter Circular Overpass Track, Gifts Toys for Boys Kids Age 6 7 8-12', 'Hotwheel.png'),
(35, 'Fisher-Price Pretend Laptop', 6, 799.99, 4, 'Pretend laptop computer activity toy with multi-color lights and 55+ songs, sounds and phrases\r\n3 Smart Stages learning levels teach the alphabet, colors, counting, greetings, and Spanish words\r\nNumber and letter keyboard buttons, screen slider, and roller help develop fine motor skills, plus mirror and light-up \"touchpad\" help foster baby\'s visual skills\r\nHinged screen folds like a real laptop for storage or take-along play\r\nFor infants and toddlers ages 6-36 months\r\n', 'Learning Toy for Baby and Toddler with Light Music and Smart Stages Educational Content, Laugh & Learn', 'LaptopToy.png'),
(36, 'Remote Control Robot Dog', 6, 6500, 4, '🐶【Interactive Robot Dog】This clever remote control puppy dog could perform a different dance with different music, and your baby will enjoy the pleasure of these actions. When your child touches the robotic dog\'s jaw, it will respond with a sound on the ground. When the eyes of the RC robot dog toy are bright, they are in the shape of a heart and emit a faint yellow light, which makes you feel very warm.\r\n❤️【Multifunctional robot dog toy】You only need to use the remote control to make the smart robot dog do many actions, forward, backward, turn left, turn right, handstand, sit down, act like a spoiled child, push up, sing, dance, etc. Fun and fun bionic action, easy to achieve with one click that is like a real puppy to accompany your children. It is not only easy for kids to interact with this robot toy, but can help kids exercise finger flexibility and auditory discrimination.\r\n🔥【Intelligent Programmable RC Dog】To inspire the imagination, programming the remote control robot dog to perform different actions is available. press multiple desired action buttons, up to 100 actions can be programmed, and after completion, multiple actions can be realized continuously show. let the robot do different actions, and let your child learn the easiest programming.\r\n🌸【High Quality and Safe Material】The smart robot toy is made of non-toxic ABS plastic, BPA-free, with smooth rounded edges, no sharp corners, and a sturdy design that will not break easily, totally safe for kids. The robot dog toy has a built-in rechargeable battery with 3.7V 600mAh (included). Please note: The remote control needs 2 AAA batteries to operate.', 'For Boys Girls Age 3 4 5+, Programmable Interactive & Smart Dancing Walking RC Robot Dog Toys with Touch Function, Voice Control, Electronic Dog Pets Toys', 'Dog.png'),
(37, 'First Act Discovery Disney Princess Electronic Keyboard', 6, 450, 10, 'MAKE MUSIC Let your little musician’s creativity soar with the First Act Disney Princess Keyboard!\r\nRECORD THEIR SONGS Record and playback the creative tunes your little one creates!\r\nEDUCATIONAL MUSICAL TOYS The First Act Princess Keyboard is great for developing their motor skills!\r\nPLAY ALONG The included sounds and rhythms will build up their musical creations!\r\nDISCOVER FIRST ACT First Act provides fun, vibrant, easy-to-use instruments for tiny beginners!', '22 Inch - 37 Keys – Make Real Music, Sized for Kids - Record, Playback, Volume Control - Musical Instruments for Toddlers and Kids', 'Piano.png'),
(38, 'Meland Basketball Hoop Indoor', 6, 1700, 7, 'Cheer Up for The Successful Shooting with Electronic Scoreboard. Calculated the score digitally and displayed automatically with real rousing cheers, Meland new arrival door basketball hoop creates a more realistic hot atmosphere like in the crowded gym and allows these basketball-loving kids for indoor basketball game. A nice touch in boys room decor, bedroom and classroom. Also it is also suitable for adults in the home and office.\r\nElectronic Basketball Scoreboard Hoop with 2 Scoring Modes for Extra Fun. Your active boys can get different scores in the two scoring methods, which not only stimulates your kids desire to exercising, but also enables your kids to learn more about perseverance, compete and cooperate. Meland basketball toys set for little beginners to develop hand eye coordination, focusing on targets and body movement.\r\nHeavy-Duty Steel Rim & Shatterproof/Resistant Backboard for Long Durability. Meland over the door basketball hoop indoor features with steel rim, shatterproof backboard and strong ball net as well as the thick shock-proof sponge strips of the backboard reduce scratches on the door and noise. Premium quality extend this mini basketball hoop toy service life and sturdy.\r\nDunking Like a Basketball Pro with Bounce Back Design For An Authentic Basketball Experience. The break-away rim with spring action stimulates the real feeling of playing basketball and allows your kids to slam dunk and shoot with ease anytime anywhere.\r\nFlexible, Space-Saving & Safe Mini Basketball Hoop Set for Kids. This basketball mini hoop doesn’t take up too much house space compared to the vertical one and safe enough for your little ones. The size is appropriate to be installing in office, classroom, dormitory, house or everywhere you want, it is convenient for you to carry out. Not only suitable for children.', 'Mini Basketball Hoop for Door with Electronic Scoreboard, 4 Balls & Air Pump, Basketball', 'ElectronicBB.png'),
(39, 'Smalody Interactive Electronic Plush Toy', 6, 1650, 3, '💝【WHO AM I】Hello, my little master! I’m a very adorable robot kitten cat, and look like a real one. I can jump, you just a touching tap or handclap,I will move towards you and meow, and of course I hope you will like it or move with me. Oh, I am also obedient, following your command is my obligation. With versatility, I have my little emotions, I will make a cute meow and also make an unhappy hoarse sound. If you like, I can Stand upside down for you -:)\r\n💝【I HAVE COOL LED EYES】When moving, my eyes will emit cool, edge-colored lights. I will be your good Playmate,play with me,you will not alone and boring; no matter the birthday party, school event or holiday celebration you can bring me.Surely,No need for stage, once I receive your command, my paws will be activated immediately. I have so much potential, so don’t miss me out! I will bring endless fun to you!\r\n💝【I AM SAFE】I am meek and well-behaved robot kitten, I don’t hurt people. Because I have soft plush material, skin-friendly and safe, filled with PP cotton, good resilience, and fine workmanship.With a smooth and soft body, I\'m sure you will like to hug me, but please don\'t ride me. (As I am small with size 26*28.5cm)\r\n💝【I AM EASILY OPERATED】Dear master,you can let your parants help you to use a screwdriver to open the cover of the battery box (at my belly), and Load the 4 * AA batteries; adjust the switch to the [ON] position; then you can tap my body or give a handclap.That\'s all!TYE ME!\r\n💝【EASY TO FEED ME】Oh, my little master! Please remember to change batteries if I am weak. Otherwise, I will fall asleep. By the way, Smalody store, who gave me life also provides 30-day free refund or replacement. So you don’t need to worry about any problem.', 'Upgrade with LED Light Eyes Animated Sound Control Electronic Pet, Robot Cat Kitten Toys', 'Cat.png'),
(40, 'Connect 4 Classic Grid Board Game', 3, 450, 10, 'RULE THE GRID 4 THE WIN: With this classic Connect 4 game, featuring a sleek modern style, players go head-to-head as they try to get 4 of the same color discs in a row to win\r\nEXCITING STRATEGY GAME: Challenge a friend to rule the grid! Strategy drives the competition in this Connect 4 board game. Line \'em up, block opponents, and be the first to get 4 in a row to win\r\nMODERN STYLE & COOL COLORS: The Connect 4 Classic Grid kids game takes the popular game one step further with a sleek style and cool colors to keep players glued to the grid\r\n3 WAYS TO PLAY: Choose classic Connect 4 gameplay, the free-for-all Connect 4 Frenzy variation, or a third option that lets players drop a disc or eject one from the bottom with the pop-out feature\r\nEASY, FAST, AND FUN GAME FOR FAMILIES: Easy to learn and simple to set up, the Connect 4 Classic Grid family game for 2 players is a fast-playing favorite\r\nFUN GIFTS FOR GIRLS AND BOYS: Strategy Games are excellent gifts for families or gifts for kids that love playing classic board games\r\n', '4 in a Row Game, Strategy Board Games for Kids, 2 Player Board Games for Family and Kids', 'Connect4.png'),
(41, 'Scrabble Board Game', 3, 349.99, 10, 'CLASSIC CROSSWORD GAME: Get family and friends together for a fun game night with the Scrabble board game! Put letters together, build words, and earn the most points to win\r\nWOODEN TILES AND RACKS: This edition of the Scrabble game features 100 wooden letter tiles and wooden tile racks. The textured gameboard helps tiles stay on the board\r\nRACK UP THE POINTS: Scrabble letters are worth points, and premium squares on the gameboard multiply the score. Surprise opponents with 2-letter words, challenge their choices, and strategize to win\r\nGAME FOR 2-4 PLAYERS: Go for classic Scrabble gameplay in a head-to-head face-off, or mix things up and play in teams. The game guide offers expert tips, and other ways to play this classic word game\r\nFUN FAMILY GAME: Do you remember playing Scrabble when you were a kid? Introduce this fun game to your kids and grandkids! Connect over a classic board game and create memories for generations to come', 'Word Game for Kids Ages 8 and Up, Fun Family Game for 2-4 Players, The Classic Crossword Game', 'Scrabble.png'),
(42, '3D Puzzles for Adults Kids Ages 8-10 Notre Dame de Paris Architecture ', 2, 950, 10, 'Educational Toys for Children and Adults: This 3d puzzle will take 60-120 mins, need patience and focus on to building. So it’s great for improving children\'s concentration and creativity and would be a wonderful gift for your children, friends and family. Quality Materials: The pre-cut paper and EPS foam board puzzle pieces is precision made to fit perfectly together. They are rigid, durable and easy to be assembled. Don’t need any tools and glue.', 'Finished Model Size: 13.98\'\'L*7.09\'\'W*9.45\'\'H, recommend for aged 10-99. After finished the 3d puzzles, it is a nice architecture can be display as art, home decoration or collection.', 'ND.jpg'),
(43, 'Rubik\'s Cube, The Original 3x3 Cube 3D Puzzle', 2, 650, 8, 'THE ORIGINAL RUBIK’S CUBE: A combination of math, art, & science- the iconic Rubik’s Cube is here to challenge your mind. The 3x3 Cube is the world’s best-known puzzle and has fascinated fans since its 1980 launch. TWIST, TURN, LEARN: The Rubik’s Cube features 6 colored sides, each made up of 9 squares. Once the sides are jumbled up, you twist, turn, and rotate the Cube until each of the 6 sides has only 1 color. GREAT FOR ANXIETY RELIEF: This fidget toy pack is not only a fun brain puzzle, this puzzle toy is perfect to keep your hands moving in stressful moments like the classroom or the airport.', 'This brain teaser puzzle is the same speed cube that you remember from your childhood of retro toys. Do you have what it takes to solve the most iconic of all kids toys?', 'RC.png'),
(44, 'Nerf Elite 2.0 Eaglepoint RD-8 Blaster', 6, 2100, 10, 'Fire 8 darts in a row up to 90 feet (27 meters) from the blaster\'s 8-dart revolving drum. Slide the bolt backward and forward to prime the blaster. Includes 16 Official Nerf Elite foam darts. After loading the drum, you can store 8 darts in the built-in storage area for quick reloads. Take advantage of the blaster\'s detachable scope and detachable barrel to create different blaster styles for each battle or mission.', 'Nerf Elite 2.0 Eaglepoint RD-8 blaster includes a detachable scope and barrel to create different blaster styles for any mission.', 'nerf1.png'),
(45, 'Nerf N-Strike Vulcan EBF-25 Dart Blaster', 6, 950, 10, 'Massive and thrilling. Even your toughest opponent won’t know what hit him when you unleash the power of the N-STRIKE VULCAN EBF-25 blaster. Fully automatic blaster holds up to twenty-five darts and can fire up to three darts per second', 'The removable tripod folds for easy transport – or a quick escape from enemy fire', 'nerfm.png'),
(46, 'Disney Castle 216 Piece 3D Jigsaw Puzzle', 2, 2000, 10, 'No matter how large or small our puzzles, each is precision made so that every piece fits perfectly. Individual pieces are so precisely made that you can actually hear a ‘click’ when you fit a piece into the correct place. This puzzle is meant to be displayed after it\'s built. It\'s 3D, and highly durable.', 'Ravensburger’s 3D jigsaw puzzles will bowl you over with premium quality, in terms of both content and material.', 'dc3d.png'),
(47, 'HOT WHEELS 10 cars Gift Pack', 6, 350, 20, 'Since Their Debut In 1968, Hot Wheels Vehicles Have Been An Enduring Favorite Of Collectors, Car Enthusiasts And Racing Fans Of All Ages. The 10-Pack Assortment Includes A Variety Of Vehicles. Each Car Is Featured At 1:64 Scale With Realistic Details And Authentic Decos. Makes A Great Gift For Kids And Collectors Of All Ages.', 'The 10-Pack Assortment Includes A Variety Of Vehicles.', 'ht.png'),
(48, 'Uzumaki Naruto Sage Of Six Paths Mode', 4, 1500, 10, 'Save the world with this fantastic Naruto toy, part of Bandai\'s Anime Heroes anime figures range. In his Sage of Six Paths Mode, Naruto is shown with the Truth Seeking Balls behind him and comes with extra pairs of hands and his Six Paths Bo. This Anime Heroes figure depicts Naruto, the titular character of the Naruto anime and manga series. Naruto is a ninja that grows in strength throughout the series, in his Sage of Six Paths Mode he has incredible power which he uses to protect the world and his friends. Each anime action figure in this Naruto toys range is 17cm and has 17 points of articulation so you can have your Naruto figurine take all of his favourite poses from the Naruto Shippuden show. Relive iconic moments like Naruto\'s battle with Madara.', '17cm Naruto Figure With Extra Hands And Accessories', 'ns.png');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `username`, `email`, `password`) VALUES
(1, 'admin', 'admin@gmail.com', '1234'),
(2, 'crncck', 'crncck@gmail.com', '1234'),
(5, 'Cxde02', 'arruhomaun2@gmail.com', 'Ahmad12345');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`cat_id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`product_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `cat_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `product_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
